### PR TITLE
Added Iraqi and Kurdish channels

### PR DESCRIPTION
**Pull request by Mennaruuk**
I understand Kurdistan isn't a country, but it'd be nice for Kurdish users to have something to watch on Free-IPTV.

### CODE REVIEW

**Comment by Mennaruuk** [comment]
Sorry, just started committing to his, forgot about alphabetical order, and I already deleted my fork. If you merge, I can change sorting ASAP. Thank you!

**Comment by Free-IPTV** [comment]
Hi Mennaruuk,

okay but i can't take the m3u like that!

1. Please ask me in advance if you are building a new M3U
2. Take the other M3Us as an example, this is how they have to look
3. Test all streams beforehand, Al-Sumaria does not work

Although I don't actually have time for this today, I will create the IQ01_IRAQ NEW and then upload it.

Thank you for your help but please also consider this point in the future. I won't rework anything there.

**Comment by Mennaruuk** [comment]
My apologies yet again. I will do my best to confirm to the rules from now on. Thank you for the reminder, I hope you have a wonderful day.

**Comment by Free-IPTV** [comment]
> 
> 
> My apologies yet again. I will do my best to conform to the rules from now on. Thank you for the reminder, I hope you have a wonderful day.

New file is online! Thanks, also have a wonderful day. :-)

**Pull request closed without merging**
