### PR TITLE
Update US06_USA_Plex.m3u

### PR DESCRIPTION
**Pull request by ReenigneArcher**
-Added missing channels. This m3u now 100% matches Plex's US offering. Channel count increased from 66 to 118.
-Fixed channels where stream didn't match what was shown on Plex.
-Removed Camp Spoopy channel (not in Plex).
-Updated x_plex_tokens and device ids (did) to match across the urls which require those parameters.
-Fixed order of streams
-Moved Party Tyme Karaoke and Latido Music to music section

Edit: Corrected tvg-IDs... Plex changes the channel number quite frequently, so better to have just the channel name and not the numbers.

Please test. Thanks!

### CODE REVIEW

**Comment by Free-IPTV** [comment]
Hi ReenigneArcher,

Many thanks for your great support! I'm excited. :-) Yes, you can embed a Pyton script in Kodi. I don't know how to do it, but I can get help. :-)

I can't convert to an add-on, but I know a few people who might be able to do that. They program addons for Kodi. I am i.a. in the forum Kodinerds.net. This is a German forum, there are even programmers from Libreelec, Coreelec and one directly from Kodi! I could ask them if they can convert your script into an add-on.

The upcoming version Kodi 19 (Matrix) only uses Python3. All addons up to Kodi 18 have to be reprogrammed anyway.
Of course, it would be better if you create an add-on for Kodi 19 yourself. With so many PLEX channels, it's worth it! It could then also be published in the Kodinerds.net forum in the Kodinerds repo. After that, it would be a lot easier for the addon to even go into the original Kodi repo. In the Kodinerds forum and also in the Kodinerds repo there are only legal topics and legal addons.

At the moment we're at Kodi 19 at version Beta2. There would still be enough time to create an add-on. Users who speak English are also welcome in the Kodinerds forum, some of them understand it!

I got the original list from Plex from a user in the Kodinerds forum. I then rebuilt it, but there were older links in it.

Recently I got the links to the Plex music channels via the forum.

I got the original list from Plex from a user in the Kodinerds forum. I then rebuilt it, but there were older links in it. Recently I got the links to the Plex music channels via the forum.

Thanks for your great work!

Greetings from Germany :-)

**Comment by Free-IPTV** [comment]
I again, have tested the channels, only fubo sports network is not running.

**Comment by ReenigneArcher** [comment]
For fubo Sports could you try changing the `/2.m3u8` to `/0.m3u8` ?

**Comment by Free-IPTV** [comment]
I has change to 0.m3u8 and test it, there is no stream.

**Comment by ReenigneArcher** [comment]
It appears to be blocked in Europe (and maybe other places). I checked with my VPN and the stream won't load in Germany or UK (I didn't try every European country). It works for US and Canada (I didn't try any others).

I checked the stream url from their official website and it's the same as what Plex provides. Also the website won't play any content while connected to German VPN server, although it does load the m3u8 files which is interesting. As soon as I disconnect the VPN the stream loads, even without refreshing.
https://www.fubosportsnetwork.com/

I know in your read-me you state you don't want any geo blocked streams, but maybe as this playlist is the US Plex list there could be exception made? Maybe a section added similar to how you did the music streams, named GEO-RESTRICTED.

**Comment by Free-IPTV** [comment]
Hi ReenigneArcher,

all other streams from Plex work, including the music channels. It is important to work without a VPN or to use a German IP only for testing. :-) I don't have a VPN myself, I don't need that either. It's just important to me that the streams from my M3U's can be received everywhere and that the addresses are legal.

Thank you for your great help!

Incidentally, I found another address for streams today, the forum is in New Zealand. I'm a member there too.

Look there:
https://forums.whirlpool.net.au/thread/9nk6qzy3

Greetings from Germany :-)

**Comment by ReenigneArcher** [comment]
Understood...

By the way I've created some more python scripts. One to generate epg data for Pluto TV, and another to generate the m3u list. Their channels are dynamic as the live events are not always online. My script will find those channels as well, but needs to be run when the channel appears on their website. The script currently returns 297 channels. Last night it returned 300 channels as there were 3 live events.
(https://github.com/ReenigneArcher/web2tv)

Also, I think I saw that you're deleting your repository... What will the new name be? Personally I wouldn't worry about all the forks. I've seen repos with thousands of forks. Most people know to look at the head repository for the most up to date.

**Pull request merged**
