### PR TITLE
Requesting_Access

### PR DESCRIPTION
**Pull request by gammerboy**
I'm sorry I wasn't able to create an issue as per point 2.
I do agree with the rest of the terms but I'm just testing iptv rn and your's is one of the first results I got for m3u on google.

Thank you

### CODE REVIEW

**Comment by luke2m** [comment]
I’d also love access.

**Comment by Free-IPTV** [comment]
Okay... a donation you can make here:

https://paypal.me/FreeIPTVGitgub (YES... Haha, the name FreeIPTVGitgub is correct)

**Comment by Free-IPTV** [comment]
Hi @gammerboy,

please check your gmail! ;-)

**Comment by patrickdrd** [comment]
is donation obligatory? for access?
in any way I would like access too please

**Comment by Free-IPTV** [comment]
Hi @patrickdrd 

And here we go again in the wrong direction, I have no desire to do so, conversation locked, closing time!

**Pull request closed without merging**
