### PR TITLE
Add Portugal.m3u8

### PR DESCRIPTION
**Pull request by cyberlimbo**
Sorry if it is ".m3u8"

### CODE REVIEW

**Comment by Free-IPTV** [comment]
> 
> 
> Sorry if it is ".m3u8"

This .m3u8 has only Audio no TV.

**Comment by cyberlimbo** [comment]
Oh, sorry..
I'll publish the correct one soon ;)

**Comment by Free-IPTV** [comment]
> 
> 
> Sorry if it is ".m3u8"

Thanks for your list, but it is not usable that way.

Only the TV channel Porto Canal works, many other channels are not channels from Portugal, e.g.
France 24, Sky News, Deutsche Welle and so on.

Channels with audio only, are also not usable for a TV channel list. If I have time, maybe I'll create one
List of TV channels from Portugal that can also be received outside of Portugal, this is also important for my lists.

regards

**Comment by Free-IPTV** [comment]
Look at my newest list, these are free tv stations from Portugal! PT01_PORTUGAL.m3u

**Comment by cyberlimbo** [comment]
> Look at my newest list, these are free tv stations from Portugal! PT01_PORTUGAL.m3u

I just checked.
They're wrong.. some are spanish others are brazilian (not the same as portuguese). 
Today i will update it with the right free iptv list, dont worry ;)

**Comment by Free-IPTV** [comment]
Okay, I can't speak Portuguese, so I didn't notice it. I thank you. :-)

**Pull request closed without merging**
