### PR TITLE
Add Brazilian Channels

### PR DESCRIPTION
**Pull request by joseanderson1995silva**
Some Brazilian Channels.
IPTV Source: https://listaiptv.gratis/

### CODE REVIEW

**Comment by Free-IPTV** [comment]
Hi joseanderson1995silva ,

i has renamed BR01_BRAZIL_Pluto.m3u to BR02_BRAZIL_Pluto.m3u, Do ist also in your fork.

Look at the files USxx, every provider has a another number.

**Comment by Free-IPTV** [comment]
Shit... i has renamed BR01_BRAZIL_Pluto.m3u in BR02_BRAZIL_Pluto.m3u and now i can accept the pull request. I has copy the new BR01_BRAZIL.m3u und upload. I think, the best is, you delete your fork and make a new fork of my repo. Sorry,,,

Thank yout for your great work. these days i will change the tvg-logo= to imgur.com :-)

**Comment by Free-IPTV** [comment]
Thank you for your help and sorry for my mistake. :-)

**Comment by joseanderson1995silva** [comment]
No problems.

**Pull request closed without merging**
