### PR TITLE
Update GR01_GREECE.m3u

### PR DESCRIPTION
**Pull request by stavpup**
removed "github.com/Free-IPTV" reference inside a channel

### CODE REVIEW

**Comment by Free-IPTV** [comment]
Sorry my friend but THAT stays in there. ;-) This repo is a lot of work, it's all free and so that I can get at least a few donations, my repo is there. Please allow me to do that! :-)

**Comment by stavpup** [comment]
Sorry, I did not know it was on purpose.

**Comment by Free-IPTV** [comment]
All good. There is a lot of work in this project and what makes my repo different from so many:
All streams are free and legal
It is updated regularly
We now have a lot of countries in there

**Comment by stavpup** [comment]
I noticed that there are greek channels in other lists. Will you add them in the greek list? 
e.g.

#EXTINF:-1 tvg-name="Montreal Greek TV" tvg-id="Montreal Greek TV" tvg-logo="https://i.imgur.com/eNu3N0f.png" group-title="CANADA",Montreal Greek TV
http://94.130.180.175:8081/live/greektv/playlist.m3u8

**Comment by stavpup** [comment]
Another one from Canada
NET TORONTO WEB TV LIVE (<a href="https://live.streams.ovh:443/NetvToronto/NetvToronto/playlist.m3u8">https://live.streams.ovh:443/NetvToronto/NetvToronto/playlist.m3u8</a>),<br>

**Comment by Zhoro-111** [comment]
No problem,next update.Thanks

**Comment by stavpup** [comment]
https://www.megatv.com/live/
MEGA TV

https://c98db5952cb54b358365984178fb898a.msvdn.net/live/S86713049/gonOwuUacAxM/playlist.m3u8

**Comment by Zhoro-111** [comment]
> https://www.megatv.com/live/
> MEGA TV
> 
> https://c98db5952cb54b358365984178fb898a.msvdn.net/live/S86713049/gonOwuUacAxM/playlist.m3u8

Ok,I will do a pull request for you.Thanks

**Pull request closed without merging**
