### PR TITLE
Add most watched Czech televisions

### PR DESCRIPTION
**Pull request by pervoj**

### CODE REVIEW

**Comment by Free-IPTV** [comment]
Hi pervoj,

sorry but all streams with 

o2tv.cz

doesn´t work. 

The streams of NOVA are okay, is the original streaming address, Nova use:

nova-live.ssl.cdn.cra.cz

As I can see, you removed the streams from o2tv.cz with the second pull request. 

From the Prima channels only CNN Prima NEWS works, The other streams doesn´t work! i thing, they ere geo-blocked.

Please READ me readme before you make a pull-request.

Thanks you for your help! :-) You can make a new pull-request with streams they are working. I have no time to edit all this after Pull-request.

**Comment by pervoj** [comment]
Everything works for me (not counting ČT). How can I check if is stream geo-blocked?

**Comment by Free-IPTV** [comment]
Hi @pervoj,

it´s important to test the streams outside the country, where it´s comes. With VPN (IP outside CZ) you can test this.
All NOVA streams works but from the Prima streams only CNN Prima NEWS works.

**Comment by Zhoro-111** [comment]
Yeah,same to me last night when I tested (France) only Nova streams worked and PrimaNews.

**Pull request closed without merging**
