### PR TITLE
Get rid of redundant https://

### PR DESCRIPTION
**Pull request by CryoRenegade**

### CODE REVIEW

**Comment by Free-IPTV** [comment]
Hi @CryoRenegade ,

why should I delete the second line in the m3u's? If you know the structure of an m3u, you will see that this makes the first line incorrect.

Just take a look at the ZZ_PLAYLIST_ALL_TV, then you will see the meaning and purpose of the first two lines in all of my m3u's. This works wonderfully in Kodi, VLC and also in the Hypnotix app (Linux-Mint(read me readme!)), it has never bothered anyone.

Thank you for using my m3u's. ;-)

**Comment by Zhoro-111** [comment]
> Hi @CryoRenegade ,
> 
> why should I delete the second line in the m3u's? If you know the structure of an m3u, you will see that this makes the first line incorrect.
> 
> Just take a look at the ZZ_PLAYLIST_ALL_TV, then you will see the meaning and purpose of the first two lines in all of my m3u's. This works wonderfully in Kodi, VLC and also in the Hypnotix app (Linux-Mint(read me readme!)), it has never bothered anyone.
> 
> Thank you for using my m3u's. ;-)

It will be nice to fill up with a live cam for every country instead of removing :)

**Comment by Free-IPTV** [comment]
> 
> It will be nice to fill up with a live cam for every country instead of removing :)

Hi @Zhoro-111 

okay, that would be an idea too. :-) I think about it, so that there is a working link in there. I also need more advertising for my project, it's a lot of work, more donations would be nice. You help me so much here in this project! I thank you. :-)

**Comment by Free-IPTV** [comment]
Hi @CryoRenegade,

have a look in the new US01_USA, there is a solution. Haha... i need advertise. This comes in all my M3U´s. Thank you. :-)

**Pull request closed without merging**
