### PR TITLE
Added and fixed some streams

### PR DESCRIPTION
**Pull request by musuruan**
These are the remaining streams I had collected.

### CODE REVIEW

**Comment by Free-IPTV** [comment]
Hi,

pleass do not create new files. When you want to do this, talk aboout this before. Okay?

Now i have to look what about this file, we have an conflict. Another User has also change this file:

Conflicting files
US01_USA.m3u

**Comment by Free-IPTV** [comment]
Please update your fork first, i can´t accept the pull-request. there are to many change from another User in this file:

Conflicting files
US01_USA.m3u

**Comment by musuruan** [comment]
The pull request was merge-able when I submitted it. I will rebase on the current master.

**Comment by Free-IPTV** [comment]
The US01_USA.m3u, wher you has edit, was an old File from my Master. Github has displayd this!

Conflicting files
US01_USA.m3u

When you edit files:

1. Sync with my master before you edit the copy of my files
2. 2. Look in my repo at Pull-Request

Is there a Pull-Request of the same file, which you want to edit, then wait!

Whe i has accept this Pull-Request of anoter User. then Update your fork and then you can edit the same file and make a Pull.Request. 

Thank you. :-)

**Pull request closed without merging**
