### PR TITLE
Update Plex m3u

### PR DESCRIPTION
**Pull request by ReenigneArcher**
-Added new channels.
-Added unique channel identifier
-Add channel number
-Simplified URLs. These are the urls provided by plex's api.

Probably my last commit for Plex. Check out my repo here if you want to generate m3u/epg for plex automatically. https://github.com/ReenigneArcher/web2tv

### CODE REVIEW

**Comment by Free-IPTV** [comment]
Hi, ReenigneArcher,

thank you for your great work! What about the X-Plex token =? Does it expire at some point, after a few days? Not everyone knows or uses your add-on to then create a new M3U with new tokens. If the token doesn't expire, I can approve your pull request. :-)

many Greetings

**Comment by ReenigneArcher** [comment]
The token I put in the pull request urls is the same token most of your urls had before. Not sure where that token came from, but my guess is it's a guest token.

If you use my plugin you'll need to supply their own token as an argument.

**Comment by Free-IPTV** [comment]
okay thank you Pull request is accepted. Because of the plugin, I don't have Linux. Also have no idea about Linux. I grew up with Windows. ;-) My Kodi runs on a Raspi4 with Libreelec and Kodi 18.9. If I have time, I can test your plugin.

Greetings

**Comment by Free-IPTV** [comment]
Sorry, back to the previous version because:

1. Complete sorting was gone
2. Plex channels in the ZZ_PLAYLIST_ALL_TV in were i.a. also in the list US01_USA

If you make an Pull-Request, dont add parameter like tvg-chno=
Please use the same structure of my existing M3Us! Thanks. :-)

**Comment by ReenigneArcher** [comment]
> 
> 
> okay thank you Pull request is accepted. Because of the plugin, I don't have Linux. Also have no idea about Linux. I grew up with Windows. ;-) My Kodi runs on a Raspi4 with Libreelec and Kodi 18.9. If I have time, I can test your plugin.
> 
> Greetings

My script is not a kodi plugin. It runs in windows, linux, mac, etc... anything you can install python on. I run it in Windows 10. Your raspberry pi is running linux :P

**Pull request merged**
