### PR TITLE
Italian local stream update

### PR DESCRIPTION
**Pull request by musuruan**
I added and updated some streams

### CODE REVIEW

**Comment by Free-IPTV** [comment]
Hi Musuruan

thank you for your great help! :-)

Please not use like this � . I has change this and now i have to change it too. Please use a and e... The file must have the format UTF-8 Thank you

**Comment by Free-IPTV** [comment]
Look, this was the message: 

We’ve detected the file encoding as ISO-8859-1. When you commit changes we will transcode it to UTF-8.

**Comment by musuruan** [comment]
What's the sense of using UTF-8 if I cannot use UTF-8 chars?

**Comment by Free-IPTV** [comment]
The streams are not only from people from Italy but from many other countries. Most have set the character set for their own country in their system. With special characters like yesterday, they have confused characters in their Kodi or VLC player. In the UTF-8 format, all of them have clean text with no tangled characters. This is the important reason to always save an M3U in UTF-8 format. For example, you can use Notepad++ to modify your M3U. There you can choose the menu coding and then UTF-8.  I thank you for your understanding.

**Pull request merged**
