### PR TITLE
Italian local streams update

### PR DESCRIPTION
**Pull request by musuruan**

### CODE REVIEW

**Comment by Free-IPTV** [comment]
Hi musuruan,

now has 2 people edit the same file, there is an conflict. Hmmm, i look, to solve this manually. Thanks for your help! :-).

**Comment by Free-IPTV** [comment]
I has change this manually. Why do you try to remove this 2 streams?

#EXTINF:-1 tvg-id="" tvg-name="Minerva Bizzarro Movies" tvg-logo="https://i.imgur.com/GQG22im.jpg" group-title="ITALY",Minerva Bizzarro Movies
https://minerva-bizzarromovies-1-it.samsung.wurl.com/manifest/playlist.m3u8
#EXTINF:-1 tvg-id="" tvg-name="Minerva Cinema Segreto" tvg-logo="https://i.imgur.com/fuvc0QF.jpg" group-title="ITALY",Minerva Cinema Segreto
https://minerva-cinemasegreto-1-it.samsung.wurl.com/manifest/playlist.m3u8

**Comment by musuruan** [comment]
Because they are already present in the same file under "Bizzarro Movies" and "Cinema Segreto".

**Comment by Free-IPTV** [comment]
> 
> 
> Because they are already present in the same file under "Bizzarro Movies" and "Cinema Segreto".

Ahhm okay, my mistake, sorry. I correct this at the next update. Thanks for your help!

**Pull request closed without merging**
