### PR TITLE
Update TR01_TURKEY.m3u

### PR DESCRIPTION
**Pull request by oltulu**

### CODE REVIEW

**Review by Free-IPTV — APPROVED** [review]

**Comment by Free-IPTV** [comment]
Hi,

thank you for your help. :-)

**Comment by Free-IPTV** [comment]
I has checkt these channels, these channels are not workong outside turkey:
TRT 2
TRT Spor 1
TRT Spor 2
TRT Belgesel

I am searching for the stream and edit the m3u. :-)

**Comment by oltulu** [comment]
I've tried it now. It works.

**Comment by Free-IPTV** [comment]
Hi Oltulu, okay, ich check this these days and when it work, ich put these channels back into the file and i adding some new stream from turkey. :-)  Thank you!

**Comment by Free-IPTV** [comment]
I has test the 4 channels, in germany comes an error, can´t open the stream for this:
TRT 2
TRT Spor 1
TRT Spor 2
TRT Belgesel
i think, it´s GEO-BLOCKING. I has only tv-stations in my .M3U´s, which you can see in all other countries WITHOUT VPN. I am not a friend of VPN, Too much illegal activity is being done with it. ;-) These days commes more FREE tv-stations for this file. :-)

**Pull request merged**
