### PR TITLE
Italian streams update

### PR DESCRIPTION
**Pull request by musuruan**
Hi! I've added a lot of Italian stream and I also split them in two files (one was becoming too big to handle). I also updated and added some other streams.

### CODE REVIEW

**Comment by Free-IPTV** [comment]
Hi musuruan,

thanks for your great work. I have one request for you, no streams in English into the M3U with Test Germany. ;-) For new dates, please contact me beforehand in the future because there are medium. over 2900 streams in the repo and if that gets even more, I won't manage to maintain them anymore. At 3000 streams it ends. Thanks for your great help!

Greetings from Germany :-)

**Comment by musuruan** [comment]
>  I have one request for you, no streams in English into the M3U with Test Germany. ;-)

Where is the correct place for DW English? 

Thank you for your valuable source of *legal* streams.

**Comment by Free-IPTV** [comment]
Hi musuruan,

I always make sure that the streams for each country are in the respective language. At DW in English, let's put them in
UK01_UNITED_KINGDOM, I would say. In UK01_UNITED_KINGDOM there are some streams in Persian anyway but they are for people in england who come from the far east but live in england. It's not always easy. ;-)

You are a great help to me!!! Thank you.  :-)

Mine ZZ_PLAYLIST_ALL_TV now has over 3000 streams. With over 3000 streams, I slowly have to make sure that everything stays up to date.

**Comment by Free-IPTV** [comment]
... and i take tomorrow DW english in the other M3U. :-)

**Pull request merged**
