### PR TITLE
Italian/Maltese/US stream update

### PR DESCRIPTION
**Pull request by musuruan**
Some more updates

### CODE REVIEW

**Comment by Free-IPTV** [comment]
Hi Musuruan,

thank you! :-)

**Comment by Free-IPTV** [comment]
Hi Musuruan,

please pay attention, no blank line at the end. I'll change that and upload again. Your changes are included. :-)

Thank you. :-)

**Comment by musuruan** [comment]
It seems you reverted these and other changes:
https://github.com/Free-IPTV/Countries/commit/246ab4aa3e9431a598347c3fc9c91d4775e19b58

**Comment by Free-IPTV** [comment]
Wait am moment, i am looking. Now if anything is wrong, I will correct it. Sorry

**Comment by Free-IPTV** [comment]
I make a new Upload, i has take the wrong files.. ;-)

**Pull request merged**
